In [42]:
import psycopg2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from  sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler

from sklearn.cluster import DBSCAN
from sklearn.cluster import AgglomerativeClustering

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.linear_model import ElasticNetCV
from sklearn.model_selection import RandomizedSearchCV

from sklearn import metrics

%matplotlib inline

In [2]:
# Query modeling_data2 table from PostgreSQL database

try:
    conn = psycopg2.connect(user="cohort17",
                            password="Cohort17Movies",
                            host="moviesdb.ce8d6g1pa5lm.us-east-1.rds.amazonaws.com",
                            port="5432",database="moviesdb")

    dbquery = "select * from modeling_data2"
    
    movies = pd.read_sql_query(dbquery, conn)

except (Exception, psycopg2.Error) as error :
    print ("Error while fetching data from PostgreSQL", error)

finally:
    if(conn):
        conn.close()

In [3]:
# Create week_number feature from release date, create input and output datasets, and create train/test split

movies['releasedate']=pd.to_datetime(movies['releasedate'])
movies['week_number']=movies['releasedate'].dt.week

X = movies.drop(['primarytitle','releasedate','domesticgross'], axis=1)
y = movies['domesticgross']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)

In [4]:
# Impute missing values in training and test datasets with median value from test dataset

median_imputer = SimpleImputer(missing_values=np.nan, strategy='median', copy=False, fill_value=None)
median_imputer.fit(X_train)
X_train = median_imputer.transform(X_train)
X_test = median_imputer.transform(X_test)

In [5]:
# Scale values of training and test datasets using min/max scaler fit on training dataset

scaler = MinMaxScaler(copy=False)
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
genre_list = ['action',
              'comedy',
              'drama',
              'adventure',
              'biography',
              'horror',
              'crime',
              'documentary',
              'animation',
              'romance',
              'mystery',
              'thriller',
              'scifi',
              'fantasy',
              'family']
genres = movies[genre_list]

In [40]:
clustering = DBSCAN(min_samples=25).fit(genres)
movies['genre_cluster'] = clustering.labels_
movies['genre_cluster'].value_counts()

-1     967
 2     153
 15    145
 13    136
 12    134
 16    133
 23    117
 19    101
 4      98
 9      79
 8      73
 27     59
 28     53
 21     52
 5      48
 11     47
 17     46
 3      44
 24     43
 7      41
 20     39
 0      38
 29     36
 26     34
 22     32
 25     31
 18     30
 1      30
 10     28
 14     25
 6      25
Name: genre_cluster, dtype: int64

In [41]:
movies[genre_list + ['genre_cluster']].groupby(['genre_cluster']).mean()

,action,comedy,drama,adventure,biography,horror,crime,documentary,animation,romance,mystery,thriller,scifi,fantasy,family
genre_cluster,,,,,,,,,,,,,,,
-1,0.281282,0.347466,0.412616,0.218201,0.085832,0.172699,0.146846,0.032058,0.04757,0.104447,0.168563,0.174767,0.14788,0.199586,0.193382
0,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
1,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000
2,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
3,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000
4,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
5,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000
6,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000
8,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
9,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000
10,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
11,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
12,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000
13,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
14,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000
15,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
16,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
18,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
19,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000
20,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000
21,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
22,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000
23,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
24,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000
25,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
26,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
27,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,1.000000,1.000000,0.00000,0.000000,0.000000
28,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
29,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000

In [48]:
clustering = AgglomerativeClustering(n_clusters=30).fit(genres)
movies['genre_cluster'] = clustering.labels_
movies['genre_cluster'].value_counts()

19    156
29    153
17    137
11    135
25    134
21    133
27    130
1     118
18    117
0     115
6     107
5     104
14    101
7      95
3      93
4      90
8      90
2      87
9      84
15     76
10     75
28     75
24     74
20     73
22     73
16     62
23     61
13     59
12     57
26     53
Name: genre_cluster, dtype: int64

In [49]:
movies[genre_list + ['genre_cluster']].groupby(['genre_cluster']).mean()

,action,comedy,drama,adventure,biography,horror,crime,documentary,animation,romance,mystery,thriller,scifi,fantasy,family
genre_cluster,,,,,,,,,,,,,,,
0,0.452174,1.000000,0.113043,1.000000,0.008696,0.000000,0.060870,0.000000,0.000000,0.008696,0.000000,0.000000,0.000000,0.000000,0.260870
1,0.000000,0.000000,0.949153,0.000000,0.262712,0.101695,1.000000,0.000000,0.008475,0.025424,0.389831,0.016949,0.000000,0.000000,0.000000
2,0.091954,0.551724,0.609195,0.114943,0.011494,0.034483,0.000000,0.000000,0.034483,0.252874,0.000000,0.011494,0.000000,1.000000,0.045977
3,0.000000,0.731183,0.010753,0.129032,0.010753,0.000000,0.043011,0.021505,0.344086,0.096774,0.000000,0.000000,0.032258,0.225806,0.978495
4,0.588889,0.022222,0.000000,0.922222,0.000000,0.011111,0.000000,0.000000,0.000000,0.011111,0.011111,0.000000,0.000000,0.944444,0.233333
5,1.000000,0.086538,0.711538,0.000000,0.076923,0.201923,0.038462,0.000000,0.000000,0.019231,0.000000,0.307692,0.000000,0.250000,0.009615
6,0.000000,0.130841,0.000000,0.009346,0.000000,1.000000,0.000000,0.000000,0.000000,0.018692,0.037383,0.448598,0.158879,0.009346,0.000000
7,0.000000,0.000000,0.157895,0.000000,0.000000,0.621053,0.084211,0.000000,0.000000,0.000000,1.000000,1.000000,0.042105,0.000000,0.000000
8,1.000000,0.000000,0.000000,1.000000,0.066667,0.066667,0.000000,0.000000,0.333333,0.033333,0.033333,0.255556,0.000000,0.000000,0.155556
9,1.000000,0.000000,0.000000,0.261905,0.011905,0.023810,1.000000,0.000000,0.000000,0.000000,0.035714,0.571429,0.059524,0.000000,0.000000
10,0.053333,0.173333,0.106667,0.013333,0.093333,0.000000,0.053333,1.000000,0.013333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.874074,0.133333,0.014815,0.644444,0.000000,0.103704,0.000000,0.000000,0.000000,0.014815,0.044444,0.000000,0.955556,0.007407,0.000000
12,0.666667,0.000000,1.000000,1.000000,0.105263,0.000000,0.017544,0.000000,0.017544,0.087719,0.017544,0.000000,0.000000,0.000000,0.000000
13,0.220339,0.050847,1.000000,0.000000,0.016949,0.000000,0.000000,0.000000,0.000000,0.271186,0.745763,0.000000,0.423729,0.118644,0.000000
14,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.026316,0.763158,0.013158,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.513158,0.118421,0.078947,0.236842,0.000000
16,0.000000,0.096774,0.709677,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
17,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007299,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.006410,1.000000,0.000000,0.006410,0.000000,0.012821,0.025641,0.000000,0.000000,0.006410,0.070513,0.000000,0.000000,0.000000,0.000000
20,1.000000,1.000000,0.000000,0.000000,0.013699,0.000000,0.643836,0.000000,0.082192,0.054795,0.000000,0.013699,0.000000,0.000000,0.041096
21,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.196721,1.000000,0.278689,0.000000,0.000000
24,0.000000,1.000000,0.324324,0.000000,0.081081,0.000000,1.000000,0.000000,0.013514,0.121622,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,0.037736,0.377358,1.000000,0.169811,0.132075,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
27,0.000000,0.161538,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.084615,0.000000,0.000000,0.000000,0.000000,0.000000
28,0.000000,0.013333,0.880000,0.053333,0.066667,0.000000,0.000000,0.000000,0.000000,0.133333,0.000000,1.000000,0.213333,0.000000,0.000000
29,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000